### ISSUE TITLE
Random.js fails to update DB on Node v14.5.0

### ISSUE THREAD

**Issue by Venryx** [graphile/livesotope#12]
### Summary

The "pg" module used by "random.js" is outdated; it silently fails to connect on Node v14.5.0.

### Steps to reproduce

Run the "random.js" script, with Node v14.5.0; no errors will be shown, but code will fail to perform any update operations. (the awaited promise in `random()` simply never resolves)

### Expected results

I expect to see the "ranking" cells in the "people" table update, from the execution of the timer in `random.js`.

### Actual results

No database updates are performed. (confirmed by checking with pgAdmin)

### Additional context

OS: Windows 10
PostgreSQL: 13.1
Node: 14.5.0

### Possible Solution

I ran `yarn add pg@latest`, and afterward the `random.js` script began successfully updating the `people` table.

I found this solution (updating the `pg` module) from the following comment: https://github.com/brianc/node-postgres/issues/2317#issuecomment-763301994

The thread shows other people with the same issue, and some discussion on the source of the issue. (apparently due to an update to the Node `stream` module)

**Comment by Venryx** [comment]
Actually, I found that the postgraphile client has a similar issue of being unable to connect, until postgraphile and a couple other packages are updated.

Therefore, rather than updating `pg` directly (and adding it to the dependency list), I found that the connection issue can be resolved (both for the frontend and backend), by updating these packages:
```
yarn add @graphile-contrib/pg-simplify-inflector@6.1.0
yarn add @graphile/subscriptions-lds@4.11.0
yarn add postgraphile@4.11.0
yarn add subscriptions-transport-ws@0.9.18
```

However, once these packages are updated, I found that it requires that your database password be supplied (in the connection string, or as an environment variable), otherwise you get this error (for both the client and the `random.js` script):
```
internal/crypto/keys.js:324
[pg]     throw new ERR_INVALID_ARG_TYPE(
[pg]     ^
[pg]
[pg] TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received null
[pg]     at prepareSecretKey (internal/crypto/keys.js:324:11)
[pg]     at new Hmac (internal/crypto/hash.js:111:9)
[pg]     at Object.createHmac (crypto.js:143:10)
[pg]     at createHMAC (C:\Root\Apps\@V\@Modules\graphile-engine\LiveQueryBug\Attempt2\node_modules\pg\lib\sasl.js:133:17)
[pg]     at Hi (C:\Root\Apps\@V\@Modules\graphile-engine\LiveQueryBug\Attempt2\node_modules\pg\lib\sasl.js:137:13)
[pg]     at Object.continueSession (C:\Root\Apps\@V\@Modules\graphile-engine\LiveQueryBug\Attempt2\node_modules\pg\lib\sasl.js:32:24)
[pg]     at Client._handleAuthSASLContinue (C:\Root\Apps\@V\@Modules\graphile-engine\LiveQueryBug\Attempt2\node_modules\pg\lib\client.js:257:10)
[pg]     at Connection.emit (events.js:314:20)
[pg]     at C:\Root\Apps\@V\@Modules\graphile-engine\LiveQueryBug\Attempt2\node_modules\pg\lib\connection.js:115:12
[pg]     at Parser.parse (C:\Root\Apps\@V\@Modules\graphile-engine\LiveQueryBug\Attempt2\node_modules\pg-protocol\dist\parser.js:40:17) {
[pg]   code: 'ERR_INVALID_ARG_TYPE'
[pg] }
```

You can see the issue described here:
https://github.com/brianc/node-postgres/issues/2371
https://github.com/feathersjs/generator-feathers/issues/607
https://github.com/mikro-orm/mikro-orm/issues/866

I fixed it by supplying the database password, using an environment variable (and then opening a new shell):
```
PGPASSWORD=YOUR_DB_PASSWORD
```

In summary, two changes need to be made for the demo to work in Node 14.5+:
1) Update the four packages, as shown at the top of this post. (to restore compatibility with latest Node's `stream` module)
2) Add instructions to the readme about how the database password must be supplied, by setting the `PGPASSWORD` environment variable.

Would one or both of these changes be acceptable as a pull request? Or is there a different solution available/preferred?

(I'm very new to Postgraphile, and am just trying to get this live-query demo working for now, so I can evaluate its flexibility and such. With the changes above, I've managed to get the data loading on the demo page. However, the live-queries appear to not be updating; so my next task is figuring out what's wrong with the live-query system. EDIT: The live-query issue was just due to me compiling the `wal2json.dll` file [incorrectly](https://stackoverflow.com/a/66064307/2441655). With the changes above, the demo works fully now. 😃)

**Comment by benjie** [comment]
Hey :wave:  Yes updating the dependencies would be very welcome as a single PR; you should be able to do this by deleting `yarn.lock`, running `yarn` again, and then pushing the updated `yarn.lock` as a PR.

As for the key issue, I think this might be related to your setup? I've not experienced that issue on Mac or Linux. I'm guessing you can fix it by using a subtly modified (e.g. more explicit) connection string? I'm not sure if that makes sense as a PR - it's been a while since I've been in the guts of this project - feel free to raise one if it's minimal effort and we'll go from there :+1: 

Thanks :raised_hands:
